name: movies
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

  #------------------------PACKAGES-------------------#
dependencies:
  flutter:
    sdk: flutter
  #Utilitiy Packages
  dio: ^5.8.0+1
  dartz: ^0.10.1
  smooth_page_indicator: ^1.2.0+3
  logger: ^2.5.0
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  awesome_dialog: ^3.2.1
  card_swiper: ^3.0.1
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  easy_localization: ^3.0.7+1
  animated_toggle_switch: ^0.8.4
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.2
  #Assets
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

  #State Management
  #get: ^4.7.2
  flutter_bloc: ^9.0.0
  flutter_staggered_grid_view: ^0.7.0

  #----------------------PACKAGES END-----------------#
  bloc: any
  iconsax: ^0.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #------------------------LOCAL ASSETS-------------------#
  assets:
    - assets/images/
    - assets/translations/


  #------------------------LOCAL FONTS-------------------#

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

